# Generated by Django 6.0.4 on 2026-07-14 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmaps', '0010_alter_question_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssessmentDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('track', models.CharField(choices=[('psp', 'PSP'), ('sdlc', 'SDLC')], max_length=16)),
                ('low_score_action', models.TextField()),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'dimension_key'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.SlugField(max_length=64, unique=True)),
                ('prompt', models.TextField()),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('dimension_key', models.SlugField(max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=24)),
                ('phase', models.CharField(choices=[('role_discovery', 'Role Discovery'), ('recommendation_ready', 'Recommendation Ready')], default='role_discovery', max_length=32)),
                ('best_fit_confidence', models.FloatField(default=0.0)),
                ('language', models.CharField(choices=[('en', 'English'), ('th', 'Thai')], default='en', max_length=8)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('skill_assessment_completed', models.BooleanField(default=False)),
                ('skill_assessment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('best_fit_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_fit_sessions', to='roadmaps.role')),
                ('current_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='roadmaps.role')),
                ('preferred_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_sessions', to='roadmaps.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentQuestionQValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_key', models.CharField(max_length=255)),
                ('question_id', models.SlugField(max_length=64)),
                ('q_value', models.FloatField(default=0.0)),
                ('reward_total', models.FloatField(default=0.0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('last_reward', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state_key', 'question_id'],
                'unique_together': {('state_key', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentRoleGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidance', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessment_guidance_items', to='roadmaps.role')),
            ],
            options={
                'ordering': ['role__slug', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_value', models.SmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence_indicator', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='roadmaps.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='roadmaps.questionoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['responded_at'],
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.SlugField(max_length=64)),
                ('value', models.SmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessment_answers', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['question_id'],
                'unique_together': {('session', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentFeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.SlugField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessment_feedback_events', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['question_id'],
                'unique_together': {('session', 'question_id')},
            },
        ),
    ]
