# Generated by Django 6.0.4 on 2026-08-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_seed_skill_assessment_catalog'),
        ('roadmaps', '0011_externalroadmapnode_externalroadmapedge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessmentdimension',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessment_dimensions', to='roadmaps.role'),
        ),
        migrations.AddField(
            model_name='skillassessmentquestion',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessment_questions', to='roadmaps.role'),
        ),
        migrations.AddField(
            model_name='skillassessmentquestion',
            name='topic_slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='skillassessmentquestion',
            name='topic_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='skillassessmentanswer',
            name='question_id',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='skillassessmentdimension',
            name='dimension_key',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='skillassessmentdimension',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skillassessmentfeedbackevent',
            name='question_id',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='skillassessmentquestion',
            name='dimension_key',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='skillassessmentquestion',
            name='question_id',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='skillassessmentquestionqvalue',
            name='question_id',
            field=models.SlugField(max_length=128),
        ),
    ]
