# Generated by Django 6.0.4 on 2026-04-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_rename_selected_role_and_more'),
        ('roadmaps', '0003_remove_questionoption_mastery_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='best_fit_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_fit_sessions', to='roadmaps.role'),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='preferred_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_sessions', to='roadmaps.role'),
        ),
    ]
