# Generated by Django 6.0.4 on 2026-08-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_skillassessmentdimension_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillassessmentfeedbackevent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skillassessmentfeedbackevent',
            name='session',
        ),
        migrations.DeleteModel(
            name='SkillAssessmentQuestionQValue',
        ),
        migrations.DeleteModel(
            name='SkillAssessmentFeedbackEvent',
        ),
    ]
