# Generated by Django 6.0.4 on 2026-04-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessmentsession_best_fit_role_and_more'),
        ('roadmaps', '0003_remove_questionoption_mastery_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSelectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('role', 'Role Discovery'), ('skill', 'Skill Estimation')], max_length=16)),
                ('policy_mode', models.CharField(choices=[('heuristic', 'Heuristic'), ('shadow_bandit', 'Shadow Bandit'), ('live_bandit', 'Live Bandit')], max_length=24)),
                ('candidate_question_ids', models.JSONField(blank=True, default=list)),
                ('candidate_question_codes', models.JSONField(blank=True, default=list)),
                ('pre_selection_uncertainty', models.FloatField(default=0.0)),
                ('post_answer_uncertainty', models.FloatField(blank=True, null=True)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('chosen_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_events', to='roadmaps.question')),
                ('heuristic_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heuristic_selection_events', to='roadmaps.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_events', to='assessments.assessmentsession')),
                ('shadow_bandit_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow_bandit_selection_events', to='roadmaps.question')),
            ],
            options={
                'ordering': ['selected_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBanditStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('role', 'Role Discovery'), ('skill', 'Skill Estimation')], max_length=16)),
                ('pulls', models.PositiveIntegerField(default=0)),
                ('cumulative_reward', models.FloatField(default=0.0)),
                ('mean_reward', models.FloatField(default=0.0)),
                ('last_selected_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_stats', to='roadmaps.question')),
            ],
            options={
                'ordering': ['stage', 'question_id'],
                'unique_together': {('question', 'stage')},
            },
        ),
    ]
