# Generated by Django 6.0.4 on 2026-08-23 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_skillassessmentfeedbackevent_unique_together_and_more'),
        ('roadmaps', '0011_externalroadmapnode_externalroadmapedge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessableTopicSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_key', models.SlugField(max_length=128, unique=True)),
                ('key', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('title_th', models.CharField(blank=True, default='', max_length=255)),
                ('node_slugs', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodes', models.ManyToManyField(blank=True, related_name='assessable_topic_sets', to='roadmaps.externalroadmapnode')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessable_topic_sets', to='roadmaps.role')),
            ],
            options={
                'ordering': ['role__slug', 'display_order', 'set_key'],
                'unique_together': {('role', 'key')},
            },
        ),
    ]
