# Generated by Django 6.0.4 on 2026-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_role_info_gain_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='phase',
            field=models.CharField(choices=[('role_discovery', 'Role Discovery'), ('role_ambiguity', 'Role Ambiguity'), ('skill_assessment', 'Skill Assessment'), ('recommendation_ready', 'Recommendation Ready'), ('completed', 'Completed')], default='role_discovery', max_length=32),
        ),
        migrations.AlterField(
            model_name='questionselectionevent',
            name='policy_mode',
            field=models.CharField(choices=[('heuristic', 'Heuristic'), ('core_sequence', 'Core Sequence'), ('info_gain', 'Information Gain'), ('shadow_bandit', 'Shadow Bandit'), ('live_bandit', 'Live Bandit')], max_length=24),
        ),
    ]
