# Generated by Django 6.0.4 on 2026-08-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessabletopicset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='skill_assessment_stable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='skill_assessment_top_five',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
