# Generated by Django 6.0.4 on 2026-08-24 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_stability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldTopicMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('topic_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_marks', to='assessments.assessabletopicset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_topic_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'topic_set__set_key'],
                'unique_together': {('user', 'topic_set')},
            },
        ),
    ]
