# Generated by Django 6.0.4 on 2026-04-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessmentsession_phase_and_more'),
        ('roadmaps', '0005_remove_questionoption_dimension_signals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='scale_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='roadmaps.questionoption'),
        ),
    ]
