# Generated by Django 6.0.4 on 2026-05-11 15:57

from django.db import migrations, models


DEFAULT_SURVEY2_QUESTIONS = [
    {
        "question_id": "psp-plan-estimate",
        "prompt": "Before starting a task, I estimate size, effort, and expected completion time.",
        "dimension_key": "psp-planning",
        "display_order": 1,
    },
    {
        "question_id": "psp-plan-compare",
        "prompt": "After finishing work, I compare actual time and outcome against my original plan.",
        "dimension_key": "psp-planning",
        "display_order": 2,
    },
    {
        "question_id": "psp-quality-defects",
        "prompt": "I record defects, mistakes, or rework patterns so I can avoid repeating them.",
        "dimension_key": "psp-quality",
        "display_order": 3,
    },
    {
        "question_id": "psp-quality-review",
        "prompt": "I review my own work with a checklist before considering it complete.",
        "dimension_key": "psp-quality",
        "display_order": 4,
    },
    {
        "question_id": "sdlc-req-criteria",
        "prompt": "I can turn unclear user needs into acceptance criteria, constraints, and open questions.",
        "dimension_key": "sdlc-requirements",
        "display_order": 5,
    },
    {
        "question_id": "sdlc-design-tradeoffs",
        "prompt": "When given a feature, I can describe components, data flow, and design tradeoffs before coding.",
        "dimension_key": "sdlc-design",
        "display_order": 6,
    },
    {
        "question_id": "sdlc-dev-conventions",
        "prompt": "I can implement maintainable code that follows project structure and naming conventions.",
        "dimension_key": "sdlc-development",
        "display_order": 7,
    },
    {
        "question_id": "sdlc-test-strategy",
        "prompt": "I define quality checks and edge cases before release.",
        "dimension_key": "sdlc-testing",
        "display_order": 8,
    },
    {
        "question_id": "sdlc-release-checklist",
        "prompt": "I understand the steps needed to release software safely, including rollback or recovery.",
        "dimension_key": "sdlc-deployment",
        "display_order": 9,
    },
    {
        "question_id": "sdlc-maintain-debug",
        "prompt": "I can debug, update, and support existing software without changing unrelated behavior.",
        "dimension_key": "sdlc-maintenance",
        "display_order": 10,
    },
    {
        "question_id": "sdlc-collab-blockers",
        "prompt": "I communicate blockers, assumptions, and progress clearly during a project.",
        "dimension_key": "sdlc-maintenance",
        "display_order": 11,
    },
]


def seed_survey2_questions(apps, schema_editor):
    Survey2Question = apps.get_model("assessments", "Survey2Question")
    for question in DEFAULT_SURVEY2_QUESTIONS:
        Survey2Question.objects.update_or_create(
            question_id=question["question_id"],
            defaults=question,
        )


def unseed_survey2_questions(apps, schema_editor):
    Survey2Question = apps.get_model("assessments", "Survey2Question")
    Survey2Question.objects.filter(
        question_id__in=[question["question_id"] for question in DEFAULT_SURVEY2_QUESTIONS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_answer_scale_value_alter_answer_selected_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey2Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.SlugField(max_length=64, unique=True)),
                ("prompt", models.TextField()),
                ("dimension_key", models.SlugField(max_length=64)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "question_id"],
            },
        ),
        migrations.RunPython(seed_survey2_questions, unseed_survey2_questions),
    ]
