# Generated by Django 6.0.4 on 2026-05-11 16:02

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_SURVEY2_DIMENSIONS = [
    {
        "dimension_key": "psp-planning",
        "label": "PSP Planning",
        "track": "psp",
        "low_score_action": "Use a small planning log for the next 3 tasks: estimated time, actual time, variance, and one cause of delay.",
        "display_order": 1,
    },
    {
        "dimension_key": "psp-quality",
        "label": "PSP Quality Discipline",
        "track": "psp",
        "low_score_action": "Create a personal review checklist and record defects found before submitting work.",
        "display_order": 2,
    },
    {
        "dimension_key": "sdlc-requirements",
        "label": "Requirements Analysis",
        "track": "sdlc",
        "low_score_action": "Practice converting one feature idea into user need, acceptance criteria, constraints, and open questions.",
        "display_order": 3,
    },
    {
        "dimension_key": "sdlc-design",
        "label": "System Design & Architecture",
        "track": "sdlc",
        "low_score_action": "Sketch components, data flow, and two tradeoffs before implementation.",
        "display_order": 4,
    },
    {
        "dimension_key": "sdlc-development",
        "label": "Development / Coding",
        "track": "sdlc",
        "low_score_action": "Implement a small feature following existing project conventions, then refactor one part for readability.",
        "display_order": 5,
    },
    {
        "dimension_key": "sdlc-testing",
        "label": "Testing & QA",
        "track": "sdlc",
        "low_score_action": "Write one normal-case test and two edge-case checks for the next feature you build.",
        "display_order": 6,
    },
    {
        "dimension_key": "sdlc-deployment",
        "label": "Deployment & Release",
        "track": "sdlc",
        "low_score_action": "Document a release checklist: build, configuration, migration, smoke test, rollback, and owner.",
        "display_order": 7,
    },
    {
        "dimension_key": "sdlc-maintenance",
        "label": "Maintenance & Support",
        "track": "sdlc",
        "low_score_action": "Trace one existing bug from report to root cause, fix plan, regression check, and release note.",
        "display_order": 8,
    },
]

DEFAULT_ROLE_GUIDANCE = {
    None: [
        "Use the lowest Survey 2 dimensions as execution habits to practice while working through the recommended roadmap topics.",
        "For each topic, create one small artifact that proves progress: plan, checklist, test, design note, or reflection.",
    ],
    "backend-developer": [
        "Prioritize API contracts, data modeling, automated tests, deployment checks, and production debugging practice.",
        "For each roadmap topic, produce a small backend artifact: endpoint design, schema change, test case, and release note.",
    ],
    "qa-engineer": [
        "Prioritize test design, defect classification, regression strategy, automation, and release quality gates.",
        "For each roadmap topic, produce test cases, risk notes, and a defect-prevention checklist.",
    ],
    "devops-engineer": [
        "Prioritize release planning, CI/CD safety, monitoring, incident response, and operational feedback loops.",
        "For each roadmap topic, document pipeline steps, environment assumptions, rollback strategy, and observability checks.",
    ],
    "devsecops-engineer": [
        "Prioritize secure release gates, threat modeling, vulnerability handling, and security regression checks.",
        "For each roadmap topic, add a security risk note and one verification step to the release checklist.",
    ],
    "product-manager": [
        "Prioritize requirements discovery, acceptance criteria, stakeholder alignment, prioritization, and delivery feedback.",
        "For each roadmap topic, define user value, success metric, risk, and acceptance criteria.",
    ],
    "software-architect": [
        "Prioritize architecture tradeoffs, quality attributes, technical risk, documentation, and evolutionary design.",
        "For each roadmap topic, document context, constraints, alternatives, decision, and expected quality impact.",
    ],
}


def seed_survey2_dimensions_and_guidance(apps, schema_editor):
    Survey2Dimension = apps.get_model("assessments", "Survey2Dimension")
    Survey2RoleGuidance = apps.get_model("assessments", "Survey2RoleGuidance")
    Role = apps.get_model("roadmaps", "Role")

    for dimension in DEFAULT_SURVEY2_DIMENSIONS:
        Survey2Dimension.objects.update_or_create(
            dimension_key=dimension["dimension_key"],
            defaults=dimension,
        )

    for role_slug, guidance_items in DEFAULT_ROLE_GUIDANCE.items():
        role = None
        if role_slug is not None:
            role = Role.objects.filter(slug=role_slug).first()
            if role is None:
                continue

        for index, guidance in enumerate(guidance_items, start=1):
            Survey2RoleGuidance.objects.update_or_create(
                role=role,
                display_order=index,
                defaults={
                    "guidance": guidance,
                    "is_active": True,
                },
            )


def unseed_survey2_dimensions_and_guidance(apps, schema_editor):
    Survey2Dimension = apps.get_model("assessments", "Survey2Dimension")
    Survey2RoleGuidance = apps.get_model("assessments", "Survey2RoleGuidance")
    Role = apps.get_model("roadmaps", "Role")

    Survey2Dimension.objects.filter(
        dimension_key__in=[dimension["dimension_key"] for dimension in DEFAULT_SURVEY2_DIMENSIONS]
    ).delete()

    default_orders = {role_slug: list(range(1, len(items) + 1)) for role_slug, items in DEFAULT_ROLE_GUIDANCE.items()}
    for role_slug, display_orders in default_orders.items():
        if role_slug is None:
            Survey2RoleGuidance.objects.filter(role__isnull=True, display_order__in=display_orders).delete()
            continue
        role = Role.objects.filter(slug=role_slug).first()
        if role is not None:
            Survey2RoleGuidance.objects.filter(role=role, display_order__in=display_orders).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0008_survey2question"),
        ("roadmaps", "0007_question_agree_disagree_signals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey2Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimension_key", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                (
                    "track",
                    models.CharField(
                        choices=[("psp", "PSP"), ("sdlc", "SDLC")], max_length=16
                    ),
                ),
                ("low_score_action", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "dimension_key"],
            },
        ),
        migrations.CreateModel(
            name="Survey2RoleGuidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guidance", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey2_guidance_items",
                        to="roadmaps.role",
                    ),
                ),
            ],
            options={
                "ordering": ["role__slug", "display_order", "id"],
            },
        ),
        migrations.RunPython(seed_survey2_dimensions_and_guidance, unseed_survey2_dimensions_and_guidance),
    ]
