# Generated by Django 6.0.4 on 2026-06-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessmentsession_language'),
        ('assessments', '0010_survey2questionqvalue'),
    ]

    operations = [
    ]
