# Generated by Django 6.0.4 on 2026-07-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_assessmentsession_current_role'),
        ('assessments', '0014_remove_topicmastery'),
    ]

    operations = [
    ]
