# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_merge_20260705_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey2question',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
