# Generated by Django 6.0.4 on 2026-07-11 11:14

from django.db import migrations, models


LEGACY_PHASES = ('role_ambiguity', 'completed', 'skill_assessment')


def normalize_legacy_phases(apps, schema_editor):
    AssessmentSession = apps.get_model('assessments', 'AssessmentSession')
    legacy_sessions = AssessmentSession.objects.filter(phase__in=LEGACY_PHASES)
    legacy_sessions.filter(status='completed').update(phase='recommendation_ready')
    legacy_sessions.exclude(status='completed').update(phase='role_discovery')


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_survey2question_translations'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_phases, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='assessmentsession',
            name='phase',
            field=models.CharField(choices=[('role_discovery', 'Role Discovery'), ('recommendation_ready', 'Recommendation Ready')], default='role_discovery', max_length=32),
        ),
    ]
