# Generated by Django 6.0.4 on 2026-07-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_alter_assessmentsession_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='survey2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='survey2_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Survey2Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.SlugField(max_length=64)),
                ('value', models.SmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2_answers', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['question_id'],
                'unique_together': {('session', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='Survey2FeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.SlugField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2_feedback_events', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['question_id'],
                'unique_together': {('session', 'question_id')},
            },
        ),
    ]
