# Generated by Django 6.0.4 on 2026-07-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_migrate_survey2_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey2dimension',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
