# Generated by Django 6.0.4 on 2026-04-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='roadmaps.roadmaptopic')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='roadmaps.role')),
            ],
            options={
                'ordering': ['role__name', 'display_order', 'title'],
                'unique_together': {('role', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=96, unique=True)),
                ('stage', models.CharField(choices=[('role', 'Role Discovery'), ('skill', 'Skill Estimation')], max_length=16)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('yes_no_maybe', 'Yes / No / Maybe'), ('single_choice', 'Single Choice'), ('ranked_choice', 'Ranked Choice')], max_length=24)),
                ('prompt', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('discrimination_score', models.FloatField(default=1.0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='roadmaps.roadmaptopic')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='roadmaps.role')),
            ],
            options={
                'ordering': ['stage', 'display_order', '-discrimination_score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=160)),
                ('value', models.CharField(blank=True, max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('mastery_value', models.FloatField(default=0.0)),
                ('role_weights', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='roadmaps.question')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('question', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TopicPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_mastery_threshold', models.FloatField(default=0.7)),
                ('dependency_weight', models.FloatField(default=1.0)),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='roadmaps.roadmaptopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='roadmaps.roadmaptopic')),
            ],
            options={
                'ordering': ['topic__role__name', 'topic__display_order'],
                'unique_together': {('topic', 'prerequisite')},
            },
        ),
    ]
