# Generated by Django 6.0.4 on 2026-04-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptopic',
            name='external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='external_slug',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='external_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='source_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='QuestionRoleSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_signals', to='roadmaps.questionoption')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_role_signals', to='roadmaps.role')),
            ],
            options={
                'ordering': ['question_option__question__code', 'role__slug'],
                'unique_together': {('question_option', 'role')},
            },
        ),
        migrations.CreateModel(
            name='QuestionTopicSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_delta', models.FloatField(default=0.0)),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_signals', to='roadmaps.questionoption')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_topic_signals', to='roadmaps.roadmaptopic')),
            ],
            options={
                'ordering': ['question_option__question__code', 'topic__slug'],
                'unique_together': {('question_option', 'topic')},
            },
        ),
    ]
