# Generated by Django 6.0.4 on 2026-04-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_roadmaptopic_external_id_roadmaptopic_external_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='mastery_value',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='role_weights',
        ),
    ]
