# Generated by Django 6.0.4 on 2026-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_question_item_group_question_discriminates_between_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='dimension_signals',
        ),
        migrations.AddField(
            model_name='question',
            name='trait_positive_dimension',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('yes_no_maybe', 'Yes / No / Maybe'), ('likert_5', 'Five-Point Agreement Scale'), ('single_choice', 'Single Choice'), ('ranked_choice', 'Ranked Choice')], max_length=24),
        ),
        migrations.DeleteModel(
            name='QuestionRoleSignal',
        ),
    ]
