# Generated by Django 6.0.4 on 2026-06-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0008_question_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptopic',
            name='topic_group',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
