# Generated by Django 6.0.4 on 2026-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0009_roadmaptopic_topic_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.CharField(choices=[('role', 'Role Discovery')], max_length=16),
        ),
    ]
