# Generated by Django 6.0.4 on 2026-08-18 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0010_alter_question_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRoadmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('topic_group', models.CharField(blank=True, default='', max_length=255)),
                ('node_type', models.CharField(choices=[('topic', 'Topic'), ('subtopic', 'Subtopic')], default='topic', max_length=16)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='roadmap.sh', max_length=64)),
                ('source_url', models.CharField(blank=True, default='', max_length=255)),
                ('source_version', models.CharField(blank=True, default='', max_length=64)),
                ('retrieved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='roadmaps.externalroadmapnode')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_roadmap_nodes', to='roadmaps.role')),
            ],
            options={
                'ordering': ['role__name', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRoadmapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_roadmap_edges', to='roadmaps.role')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='roadmaps.externalroadmapnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='roadmaps.externalroadmapnode')),
            ],
            options={
                'ordering': ['role__name', 'source_node__display_order', 'target_node__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='externalroadmapnode',
            index=models.Index(fields=['role', 'slug'], name='roadmaps_ex_role_id_e981f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalroadmapnode',
            unique_together={('role', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='externalroadmapedge',
            unique_together={('source_node', 'target_node')},
        ),
    ]
