"""Derive ROLE_PROFILE_WEIGHTS from the role-dimension relevance mapping.

The mapping (data/content/role_dimension_relevance.yaml) is the human-edited
artifact: ordinal levels plus rationale plus source references. This module
turns levels into numbers via the ladder defined in the mapping's meta block
and renders the generated module consumed by roadmaps/questionnaire.py.

Only the generator command, validators, and tests import this module — the
Django-free scoring path never does (it imports the generated module, which
is pure constants). See docs/scoring-methodology.md.
"""

import hashlib
from pathlib import Path

import yaml

from roadmaps.content_review import VALID_REVIEW_STATUSES, invalid_review_status_message, read_review_status
from roadmaps.questionnaire import ROLE_DIMENSIONS


RELEVANCE_MAPPING_PATH = Path(__file__).resolve().parent.parent / 'data' / 'content' / 'role_dimension_relevance.yaml'
GENERATED_MODULE_PATH = Path(__file__).resolve().parent / 'role_weights_generated.py'

KIND_TO_LADDER_KEY = {'ka': 'ka', 'families': 'family', 'specializations': 'specialization'}


def load_relevance_mapping(path: Path = RELEVANCE_MAPPING_PATH) -> dict:
    return yaml.safe_load(path.read_text(encoding='utf-8'))


def compute_mapping_digest(path: Path = RELEVANCE_MAPPING_PATH) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def derive_role_profile_weights(mapping: dict) -> dict[str, dict[str, float]]:
    ladder = mapping['meta']['weight_ladder']
    weights: dict[str, dict[str, float]] = {}
    for role_slug, role_entry in mapping['roles'].items():
        profile: dict[str, float] = {}
        for kind, ladder_key in KIND_TO_LADDER_KEY.items():
            for dimension_key, cell in (role_entry.get(kind) or {}).items():
                if dimension_key not in ROLE_DIMENSIONS:
                    msg = f'{role_slug}.{kind}.{dimension_key} is not a known dimension'
                    raise ValueError(msg)
                if dimension_key in profile:
                    msg = f'{role_slug}: dimension "{dimension_key}" appears in more than one section'
                    raise ValueError(msg)
                level = cell.get('level')
                level_weights = ladder[ladder_key]
                if level not in level_weights:
                    msg = f'{role_slug}.{kind}.{dimension_key}: unknown level "{level}" (allowed: {sorted(level_weights)})'
                    raise ValueError(msg)
                profile[dimension_key] = float(level_weights[level])
        weights[role_slug] = profile
    return weights


def derive_top_ka_codes(mapping: dict, ka_code_by_dimension: dict[str, str]) -> dict[str, list[str]]:
    """Per role: the KA codes at level ``core``, sorted by KA number."""
    top_codes: dict[str, list[str]] = {}
    for role_slug, role_entry in mapping['roles'].items():
        core_codes = [
            ka_code_by_dimension[dimension_key]
            for dimension_key, cell in (role_entry.get('ka') or {}).items()
            if cell.get('level') == 'core'
        ]
        top_codes[role_slug] = sorted(core_codes, key=lambda code: int(code.removeprefix('KA')))
    return top_codes


def render_generated_module(weights: dict[str, dict[str, float]], *, rubric_version: int, mapping_digest: str) -> str:
    lines = [
        '# GENERATED by `manage.py generate_role_weights` from',
        f'# data/content/role_dimension_relevance.yaml (rubric v{rubric_version}, sha256:{mapping_digest}).',
        '# DO NOT EDIT. Edit the mapping levels and regenerate; review the diff instead.',
        '',
        f"RELEVANCE_MAPPING_DIGEST = '{mapping_digest}'",
        '',
        'ROLE_PROFILE_WEIGHTS = {',
    ]
    for role_slug in sorted(weights):
        lines.append(f"    '{role_slug}': {{")
        lines.extend(f"        '{dimension_key}': {weights[role_slug][dimension_key]}," for dimension_key in sorted(weights[role_slug]))
        lines.append('    },')
    lines.extend(['}', ''])
    return '\n'.join(lines)


SWEBOK_REFERENCE_PATH = Path(__file__).resolve().parent.parent / 'data' / 'sources' / 'swebok_v4_ka_reference.yaml'
ROADMAP_MANIFEST_PATH = Path(__file__).resolve().parent.parent / 'data' / 'upstream' / 'roadmap_sh' / 'manifest.yaml'


def _load_known_source_anchors() -> tuple[set[str], set[str]]:
    swebok = yaml.safe_load(SWEBOK_REFERENCE_PATH.read_text(encoding='utf-8'))
    manifest = yaml.safe_load(ROADMAP_MANIFEST_PATH.read_text(encoding='utf-8'))
    ka_codes = {entry['code'] for entry in swebok['knowledge_areas']}
    manifest_files = {entry['file'] for entry in manifest['files']}
    return ka_codes, manifest_files


def _validate_sources(cell_path: str, sources, *, ka_codes: set[str], manifest_files: set[str], errors: list[str]) -> None:
    if not isinstance(sources, list) or not sources:
        errors.append(f'{cell_path}: sources must be a non-empty list')
        return
    for source in sources:
        if not isinstance(source, dict) or len(source) != 1:
            errors.append(f'{cell_path}: each source must be a single-key mapping, got {source!r}')
            continue
        ((source_kind, source_value),) = source.items()
        if source_kind == 'swebok':
            if not isinstance(source_value, dict) or source_value.get('ka') not in ka_codes:
                errors.append(f'{cell_path}: swebok source must reference a known KA code, got {source_value!r}')
        elif source_kind == 'roadmap_sh':
            if not isinstance(source_value, dict) or source_value.get('file') not in manifest_files:
                errors.append(f'{cell_path}: roadmap_sh source must reference a manifested file, got {source_value!r}')
        else:
            errors.append(f'{cell_path}: unknown source kind "{source_kind}"')


def validate_relevance_mapping(mapping: dict, *, roles_yaml_entries: list[dict]) -> list[str]:
    """Structural + cross-file checks. Returns a list of error messages."""
    errors: list[str] = []
    ka_codes, manifest_files = _load_known_source_anchors()
    ka_code_by_dimension = {
        entry['dimension_key']: entry['code']
        for entry in yaml.safe_load(SWEBOK_REFERENCE_PATH.read_text(encoding='utf-8'))['knowledge_areas']
    }

    mapped_roles = set(mapping['roles'])
    seed_roles = {entry['slug']: entry for entry in roles_yaml_entries}
    errors.extend(f'role "{missing}" is in roles.yaml but has no relevance-mapping entry' for missing in sorted(set(seed_roles) - mapped_roles))
    errors.extend(f'role "{extra}" is mapped but missing from roles.yaml' for extra in sorted(mapped_roles - set(seed_roles)))

    derived_top_codes = derive_top_ka_codes(mapping, ka_code_by_dimension)
    for role_slug, role_entry in mapping['roles'].items():
        review_status = read_review_status(role_entry)
        if review_status not in VALID_REVIEW_STATUSES:
            errors.append(invalid_review_status_message(f'Relevance mapping "{role_slug}"', review_status))
        for kind in KIND_TO_LADDER_KEY:
            for dimension_key, cell in (role_entry.get(kind) or {}).items():
                cell_path = f'{role_slug}.{kind}.{dimension_key}'
                if not str(cell.get('rationale') or '').strip():
                    errors.append(f'{cell_path}: rationale is required')
                _validate_sources(cell_path, cell.get('sources'), ka_codes=ka_codes, manifest_files=manifest_files, errors=errors)
        if role_slug in seed_roles:
            declared = list(seed_roles[role_slug].get('top_ka_codes') or [])
            derived = derived_top_codes.get(role_slug, [])
            if sorted(declared) != sorted(derived):
                errors.append(
                    f'{role_slug}: roles.yaml top_ka_codes {sorted(declared)} != core-level KAs in mapping {sorted(derived)}',
                )
    return errors


def render_from_mapping(path: Path = RELEVANCE_MAPPING_PATH) -> str:
    mapping = load_relevance_mapping(path)
    weights = derive_role_profile_weights(mapping)
    return render_generated_module(
        weights,
        rubric_version=int(mapping['meta']['rubric_version']),
        mapping_digest=compute_mapping_digest(path),
    )
