# Generated by Django 6.0.4 on 2026-07-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('roadmaps', '0010_alter_question_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('path_kind', models.CharField(choices=[('preferred', 'Preferred Role Path'), ('best_fit', 'Best-Fit Role Path')], default='preferred', max_length=24)),
                ('policy_type', models.CharField(choices=[('rule_based', 'Rule Based'), ('q_learning', 'Q Learning')], default='rule_based', max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('state_key', models.CharField(blank=True, max_length=255)),
                ('feedback_reward_applied', models.BooleanField(default=False)),
                ('feedback_reward_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='roadmaps.role')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='assessments.assessmentsession')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='roadmaps.roadmaptopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationQValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_key', models.CharField(max_length=255)),
                ('path_kind', models.CharField(choices=[('preferred', 'Preferred Role Path'), ('best_fit', 'Best-Fit Role Path')], default='preferred', max_length=24)),
                ('q_value', models.FloatField(default=0.0)),
                ('reward_total', models.FloatField(default=0.0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('last_reward', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_q_values', to='roadmaps.role')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_q_values', to='roadmaps.roadmaptopic')),
            ],
            options={
                'ordering': ['state_key', 'path_kind', 'role__slug', 'topic__display_order', 'topic__id'],
                'unique_together': {('state_key', 'path_kind', 'role', 'topic')},
            },
        ),
    ]
