# Generated by Django 6.0.4 on 2026-08-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationqvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recommendationqvalue',
            name='role',
        ),
        migrations.RemoveField(
            model_name='recommendationqvalue',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='RecommendationQValue',
        ),
    ]
