# Generated by Django 6.0.4 on 2026-05-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_recommendation_path_kind"),
        ("roadmaps", "0007_question_agree_disagree_signals"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationQValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_key", models.CharField(max_length=255)),
                (
                    "path_kind",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred Role Path"),
                            ("best_fit", "Best-Fit Role Path"),
                        ],
                        default="preferred",
                        max_length=24,
                    ),
                ),
                ("q_value", models.FloatField(default=0.0)),
                ("reward_total", models.FloatField(default=0.0)),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("last_reward", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_q_values",
                        to="roadmaps.role",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_q_values",
                        to="roadmaps.roadmaptopic",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "state_key",
                    "path_kind",
                    "role__slug",
                    "topic__display_order",
                    "topic__id",
                ],
                "unique_together": {("state_key", "path_kind", "role", "topic")},
            },
        ),
    ]
