# Generated by Django 6.0.4 on 2026-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0003_recommendationqvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="feedback_reward_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="feedback_reward_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="state_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
