# Generated by Django 6.0.4 on 2026-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_recommendation_feedback_reward_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='policy_type',
            field=models.CharField(choices=[('rule_based', 'Rule Based'), ('q_learning', 'Q Learning')], default='rule_based', max_length=32),
        ),
    ]
